# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: rpruim@gmail.com
    on_failure: rpruim@gmail.com

r_binary_packages:
  - XML
  - Rcpp
  - knitr

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  - ProjectMOSAIC/NHANES
  - ProjectMOSAIC/mosaicData
